apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: development
type: Opaque
data:
  # base64 encoded values - change these in production
  # echo -n 'admin' | base64 => YWRtaW4=
  # echo -n 'landmark-secret-pass' | base64 => bGFuZG1hcmstc2VjcmV0LXBhc3M=
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: bGFuZG1hcmstc2VjcmV0LXBhc3M=
